/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

typedef union {
    struct {
      unsigned Relay0:1;
      unsigned Relay1:1;
      unsigned Relay2:1;
      unsigned Relay3:1;
      unsigned Relay4:1;
      unsigned Relay5:1;
      unsigned Relay6:1;
      unsigned Relay7:1;
    };
    struct {
      unsigned w:16;  
    };
} RELAY_OUTS;
extern volatile RELAY_OUTS RELAYS;

/* LAT_LEDSBITS */
#define RELEAY_0 RELAYS.Relay0
#define RELEAY_1 RELAYS.Relay1
#define RELEAY_2 RELAYS.Relay2
#define RELEAY_3 RELAYS.Relay3
#define RELEAY_4 RELAYS.Relay4
#define RELEAY_5 RELAYS.Relay5
#define RELEAY_6 RELAYS.Relay6
#define RELEAY_7 RELAYS.Relay7
#define RELEAY_OUT RELAYS.w

void SetROs(uint16_t value);
void SetRelaysOut(unsigned int value);
void SetRelays();